import RelationalFoundations.DemandClosure
import RelationalFoundations.History
set_option genInjectivity false

/-!
# Support produced along an actual history

Initial demands and next-step demands are generated by a declared policy. The
policy receives the actual previous history, actual step witness, and realized
outputs of the previous support. Consequently demand generation can depend on
produced outputs; no list of all future demands is supplied in advance.

The closure result still requires `RankedSystem` and a local producer. Neither
the complete semantic rules of an external verifier nor their closure is
introduced by this interface.
-/

namespace RelationalFoundations.HistoricalSupport
open DemandClosure
universe u v r w
variable {State : Type u} {Step : State → State → Type v}
variable {Request : Type r} {requires : Request → List Request}

inductive Support (requires : Request → List Request) :
    {source target : State} → History Step source target → Type (max u v r)
  | root {state : State} {requests : List Request} (resources : Forest requires requests) :
      Support requires (.root : History Step state state)
  | extend {source middle target : State} {history : History Step source middle}
      {step : Step middle target} {requests : List Request}
      (previous : Support requires history) (resources : Forest requires requests) :
      Support requires (.extend history step)

namespace Support

def entry {source : State} : {target : State} → {history : History Step source target} →
    Support requires history → History.Occurrence history →
      (requests : List Request) × Forest requires requests
  | _, _, .root _ => fun impossible => nomatch impossible
  | _, _, .extend previous resources => fun occurrence =>
      match occurrence with
      | .last => ⟨_, resources⟩
      | .earlier old => entry previous old
termination_by structural _ _ support => support

def initialEntry {source : State} : {target : State} → {history : History Step source target} →
    Support requires history → (requests : List Request) × Forest requires requests
  | _, _, .root resources => ⟨_, resources⟩
  | _, _, .extend previous _ => initialEntry previous
termination_by structural _ _ support => support

def size {source : State} : {target : State} → {history : History Step source target} →
    Support requires history → Nat
  | _, _, .root resources => resources.size
  | _, _, .extend previous resources => previous.size + resources.size
termination_by structural _ _ support => support

inductive Address : {source target : State} → {history : History Step source target} →
    Support requires history → Type (max u v r)
  | initial {state : State} {requests : List Request} {resources : Forest requires requests} :
      Tree.ForestAddress resources → Address (.root (state := state) resources)
  | old {source middle target : State} {history : History Step source middle}
      {step : Step middle target} {requests : List Request}
      {previous : Support requires history} {resources : Forest requires requests} :
      Address previous → Address (.extend (step := step) previous resources)
  | fresh {source middle target : State} {history : History Step source middle}
      {step : Step middle target} {requests : List Request}
      {previous : Support requires history} {resources : Forest requires requests} :
      Tree.ForestAddress resources → Address (.extend (step := step) previous resources)

def addresses {source : State} : {target : State} → {history : History Step source target} →
    (support : Support requires history) → List (Address support)
  | _, _, .root resources => (Tree.forestAddresses resources).map Address.initial
  | _, _, .extend previous resources =>
      previous.addresses.map Address.old ++ (Tree.forestAddresses resources).map Address.fresh
termination_by structural _ _ support => support

theorem addresses_complete {source : State} : {target : State} → {history : History Step source target} →
    (support : Support requires history) → (address : Address support) → address ∈ support.addresses
  | _, _, .root resources, .initial address =>
      FiniteList.mappedMember Address.initial (Tree.forestAddresses_complete resources address)
  | _, _, .extend previous _, .old address =>
      List.mem_append_left _ (FiniteList.mappedMember Address.old (addresses_complete previous address))
  | _, _, .extend previous resources, .fresh address => by
      change Address.fresh address ∈ previous.addresses.map Address.old ++
        (Tree.forestAddresses resources).map Address.fresh
      exact List.mem_append_right _ (FiniteList.mappedMember Address.fresh (Tree.forestAddresses_complete resources address))
termination_by structural _ _ support _ => support

theorem addresses_length {source : State} : {target : State} → {history : History Step source target} →
    (support : Support requires history) → support.addresses.length = support.size
  | _, _, .root resources => by
      simp only [addresses, FiniteList.mapLength, size]
      exact Tree.forestAddresses_length resources
  | _, _, .extend previous resources => by
      simp only [addresses, FiniteList.appendLength, FiniteList.mapLength, size]
      rw [addresses_length previous, Tree.forestAddresses_length resources]
termination_by structural _ _ support => support

def resourceAt {source : State} : {target : State} → {history : History Step source target} →
    (support : Support requires history) → Address support → (request : Request) × Tree requires request
  | _, _, .root resources => fun address =>
      match address with
      | .initial initial => Tree.forestSubtree resources initial
  | _, _, .extend previous resources => fun address =>
      match address with
      | .old old => resourceAt previous old
      | .fresh fresh => Tree.forestSubtree resources fresh
termination_by structural _ _ support => support

/-- `none` denotes an initial resource; every other resource retains its step origin. -/
def origin {source : State} : {target : State} → {history : History Step source target} →
    (support : Support requires history) → Address support → Option (History.Occurrence history)
  | _, _, .root _, .initial _ => none
  | _, _, .extend previous _, .old address => (origin previous address).map History.Occurrence.earlier
  | _, _, .extend _ _, .fresh _ => some .last
termination_by structural _ _ support => support

theorem old_fresh_distinct {source middle target : State} {history : History Step source middle}
    {step : Step middle target} {requests : List Request} {previous : Support requires history}
    {resources : Forest requires requests} (old : Address previous) (fresh : Tree.ForestAddress resources) :
    Address.old (step := step) old ≠ Address.fresh (previous := previous) fresh := by
  intro equality
  cases equality

theorem old_injective {source middle target : State} {history : History Step source middle}
    {step : Step middle target} {requests : List Request} {previous : Support requires history}
    {resources : Forest requires requests} (first second : Address previous)
    (equality : Address.old (step := step) (resources := resources) first = Address.old second) :
    first = second := by
  cases equality
  rfl

theorem old_resource_preserved {source middle target : State} {history : History Step source middle}
    {step : Step middle target} {requests : List Request} (previous : Support requires history)
    (resources : Forest requires requests) (address : Address previous) :
    (Support.extend (step := step) previous resources).resourceAt (.old address) =
      previous.resourceAt address := rfl

theorem old_entry_preserved {source middle target : State} {history : History Step source middle}
    {step : Step middle target} {requests : List Request} (previous : Support requires history)
    (resources : Forest requires requests) (occurrence : History.Occurrence history) :
    (Support.extend (step := step) previous resources).entry (.earlier occurrence) =
      previous.entry occurrence := rfl

end Support

structure Context (producer : LocalProducer.{r,w} requires) {source target : State}
    (history : History Step source target) where
  constitution : Support requires history

/-- The policy can inspect the constituted support as well as its derived values. -/
def Context.initial {producer : LocalProducer.{r,w} requires} {source target : State}
    {history : History Step source target} (context : Context producer history) :
    List ((request : Request) × producer.Value request) :=
  Values.toList (producer.realizeMany context.constitution.initialEntry.2)

def Context.valuesAt {producer : LocalProducer.{r,w} requires} {source target : State}
    {history : History Step source target} (context : Context producer history)
    (occurrence : History.Occurrence history) : List ((request : Request) × producer.Value request) :=
  Values.toList (producer.realizeMany (context.constitution.entry occurrence).2)

def Support.context (producer : LocalProducer.{r,w} requires) {source target : State}
    {history : History Step source target} (support : Support requires history) : Context producer history where
  constitution := support

structure Policy (system : RankedSystem.{r}) (producer : LocalProducer.{r,w} system.requires)
    (Step : State → State → Type v) where
  initial : State → List system.Request
  next : {source middle target : State} → (previous : History Step source middle) →
    Step middle target → Context producer previous → List system.Request

namespace Policy
variable {system : RankedSystem.{r}} {producer : LocalProducer.{r,w} system.requires}

/-- The recursion is on the actual finite history; dependency expansion is internal. -/
def build (policy : Policy system producer Step) {source : State} : {target : State} →
    (history : History Step source target) → Support system.requires history
  | _, .root => .root (system.buildMany (policy.initial source))
  | _, .extend previous step =>
      let old := build policy previous
      .extend old (system.buildMany (policy.next previous step (old.context producer)))
termination_by structural _ history => history

/-- Continue from the support actually produced for the prefix. -/
def advance (policy : Policy system producer Step) {source middle : State}
    {history : History Step source middle} (support : Support system.requires history) :
    {target : State} → (continuation : History Step middle target) →
      Support system.requires (History.append history continuation)
  | _, .root => support
  | _, .extend previous step =>
      let old := advance policy support previous
      .extend old (system.buildMany (policy.next (History.append history previous) step (old.context producer)))
termination_by structural _ continuation => continuation

theorem advance_build (policy : Policy system producer Step) {source middle target : State}
    (history : History Step source middle) (continuation : History Step middle target) :
    policy.advance (policy.build history) continuation = policy.build (History.append history continuation) := by
  induction continuation with
  | root => rfl
  | extend previous step ih =>
      exact congrArg (fun old => Support.extend (step := step) old
        (system.buildMany (policy.next (History.append history previous) step (old.context producer)))) ih

def embed (policy : Policy system producer Step) {source middle : State}
    {history : History Step source middle} (support : Support system.requires history) :
    {target : State} → (continuation : History Step middle target) →
      support.Address → (policy.advance support continuation).Address
  | _, .root, address => address
  | _, .extend previous _, address => .old (embed policy support previous address)
termination_by structural _ continuation _ => continuation

theorem embed_injective (policy : Policy system producer Step) {source middle target : State}
    {history : History Step source middle} (support : Support system.requires history)
    (continuation : History Step middle target) : Function.Injective (policy.embed support continuation) := by
  induction continuation with
  | root => exact fun _ _ equality => equality
  | extend previous step ih =>
      intro first second equality
      exact ih (Support.old_injective _ _ equality)

/-- All earlier dependency trees survive an arbitrary positive continuation. -/
theorem advance_preserves_resource (policy : Policy system producer Step) {source middle target : State}
    {history : History Step source middle} (support : Support system.requires history)
    (continuation : History Step middle target) (address : support.Address) :
    (policy.advance support continuation).resourceAt (policy.embed support continuation address) =
      support.resourceAt address := by
  induction continuation with
  | root => rfl
  | extend previous step ih => exact ih

theorem build_old_entry (policy : Policy system producer Step) {source middle target : State}
    (history : History Step source middle) (step : Step middle target) (occurrence : History.Occurrence history) :
    (policy.build (.extend history step)).entry (.earlier occurrence) =
      (policy.build history).entry occurrence := rfl

theorem build_next_demands (policy : Policy system producer Step) {source middle target : State}
    (history : History Step source middle) (step : Step middle target) :
    (policy.build (.extend history step)).entry .last =
      ⟨policy.next history step ((policy.build history).context producer),
        system.buildMany (policy.next history step ((policy.build history).context producer))⟩ := rfl

/-- Every produced occurrence receives a valid realization of all of its demands. -/
theorem build_entry_valid (policy : Policy system producer Step) (sound : producer.Soundness)
    {source target : State} (history : History Step source target) (occurrence : History.Occurrence history) :
    Values.All sound.Valid (producer.realizeMany ((policy.build history).entry occurrence).2) :=
  producer.realizeMany_valid sound _

theorem build_initial_valid (policy : Policy system producer Step) (sound : producer.Soundness)
    {source target : State} (history : History Step source target) :
    Values.All sound.Valid (producer.realizeMany (policy.build history).initialEntry.2) :=
  producer.realizeMany_valid sound _

/-- Certification covers every internal dependency resource, not only root demands. -/
theorem build_resource_valid (policy : Policy system producer Step) (sound : producer.Soundness)
    {source target : State} (history : History Step source target)
    (address : (policy.build history).Address) :
    let resource := (policy.build history).resourceAt address
    sound.Valid resource.1 (producer.realize resource.2) := producer.realize_valid sound _

end Policy
end RelationalFoundations.HistoricalSupport
