import RelationalFoundations.ExactTransport
import RelationalFoundations.History
import RelationalFoundations.Residual
import RelationalFoundations.HistoryTransport
import RelationalFoundations.Spine
import RelationalFoundations.Presentation
import RelationalFoundations.Generation
import RelationalFoundations.ExactRealization
import RelationalFoundations.InteriorDelimitation
import RelationalFoundations.Continuation
import RelationalFoundations.BoundaryInterpretation
import RelationalFoundations.Regime
import RelationalFoundations.Turning
import RelationalFoundations.Signature
import RelationalFoundations.Quantity
import RelationalFoundations.FiberTransport
import RelationalFoundations.EquippedQuantity
import RelationalFoundations.Cardinalization
import RelationalFoundations.Interpretation
import RelationalFoundations.Perimetral
import RelationalFoundations.FormationAtOccurrence
import RelationalFoundations.MarkedQuantity
import RelationalFoundations.PerimetralSignature
import RelationalFoundations.Obstructions
import RelationalFoundations.NormativeAdequacy
import RelationalFoundations.CompositionOrder
import RelationalFoundations.FaithfulContinuation
import RelationalFoundations.FaithfulTurning
import RelationalFoundations.CircularSignature
import RelationalFoundations.CircularSpecification
import RelationalFoundations.Diagnostics
import RelationalFoundations.TransportLaws
import RelationalFoundations.FiniteInvariance
import RelationalFoundations.ConstitutiveGeneration
import RelationalFoundations.TurningDiagnostics
import RelationalFoundations.DemandClosure
import RelationalFoundations.HistoricalSupport
import RelationalFoundations.WordSupport
import RelationalFoundations.ResourceGraph
import RelationalFoundations.OutputDriven
import RelationalFoundations.HistoricalFeedback
import RelationalFoundations.FeedbackCoverage
import RelationalFoundations.TypedResources
import RelationalFoundations.HeterogeneousFeedback
import RelationalFoundations.FiniteRuleConstruction
import RelationalFoundations.FiniteRuleInstances
import RelationalFoundations.FiniteRuleCoordinates
import RelationalFoundations.ReducedWeakening
import RelationalFoundations.NativeForgettingSeparationV1
import RelationalFoundations.DependencyPaths
import RelationalFoundations.FiniteRuleScope
import RelationalFoundations.HeterogeneousInvariants
import RelationalFoundations.NativeForgettingContract
import RelationalFoundations.TypedResourceOrder

/- AXIOM_AUDIT_BEGIN -/
#print axioms RelationalFoundations.FiniteRuleCoordinates.resumed_composed_coordinates
#print axioms RelationalFoundations.FiniteRuleCoordinates.homogeneous_native_coordinates
#print axioms RelationalFoundations.FiniteRuleCoordinates.heterogeneous_native_coordinates
#print axioms RelationalFoundations.DependencyPaths.Coverage.ordered_roundtrip
#print axioms RelationalFoundations.HeterogeneousInvariants.constructed_then_forgotten
#print axioms RelationalFoundations.NativeForgettingContract.first_decision_irrecoverable
/- AXIOM_AUDIT_END -/
