import RelationalFoundations
import Tests.Separators
import Tests.QuantityLaws
import Tests.Completion
import Tests.HistoricalSupport
import Tests.OutputDriven
import Tests.FeedbackCoverage
import Tests.HeterogeneousFeedback
import Tests.FiniteRuleConstruction
import Tests.ReducedHeterogeneous
import Tests.NativeForgettingV1
import Tests.CyclicSupport
import Tests.HiddenEncoding
import Tests.RuleScope
import Tests.AuditCorrections
import Tests.ForgettingAuditScope
import Tests.FiniteRuleCoordinates
import Tests.CertifiedGrouping
set_option genInjectivity false

/- AXIOM_AUDIT_BEGIN -/
#print axioms RelationalFoundations.FiniteRuleCoordinatesTests.higher_universe
#print axioms RelationalFoundations.FiniteRuleCoordinatesTests.permuted_changes_identity
#print axioms RelationalFoundations.ForgettingAuditScopeTests.replay_tracks
#print axioms RelationalFoundations.CyclicSupportTests.cyclicComplete
#print axioms RelationalFoundations.HiddenEncodingTests.hidden_origin_recoverable
#print axioms RelationalFoundations.CertifiedGroupingTests.real_peak
#print axioms RelationalFoundations.CertifiedGroupingTests.equal_target_different_transport
/- AXIOM_AUDIT_END -/
